# Generated by Django 4.0.6 on 2023-03-02 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='账本id')),
                ('name', models.CharField(max_length=20, verbose_name='账本名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '账本',
                'verbose_name_plural': '账本',
            },
        ),
        migrations.CreateModel(
            name='preference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户偏好id')),
                ('default_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ledger.book', verbose_name='默认账本')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
            },
        ),
        migrations.CreateModel(
            name='bill_classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类id')),
                ('name', models.CharField(default='未分类', max_length=20, verbose_name='分类名')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ledger.book', verbose_name='所属账本')),
            ],
            options={
                'verbose_name': '账单分类',
                'verbose_name_plural': '账单分类',
            },
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类id')),
                ('name', models.CharField(default='未分类', max_length=20, verbose_name='分类名')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ledger.bill_classification', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '账单记录',
                'verbose_name_plural': '账单记录',
            },
        ),
    ]
