# Generated by Django 4.0.6 on 2023-03-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0007_alter_bill_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_classification',
            name='icon',
            field=models.CharField(default='cart-fill', max_length=30, verbose_name='分类图标'),
        ),
    ]
