# Generated by Django 4.1.1 on 2022-09-29 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('type', models.CharField(choices=[('movie', '电影'), ('anime', '番剧'), ('book', '图书')], default='movie', max_length=10, verbose_name='类型')),
                ('name', models.CharField(max_length=50, verbose_name='对象名')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='ToolBox/MovieRank/%Y/%m/%d/', verbose_name='封面图')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='评论')),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rank_next', to='Ranking.rankitem', verbose_name='后结点')),
                ('pre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rank_pre', to='Ranking.rankitem', verbose_name='前结点')),
            ],
        ),
    ]
