# Generated by Django 4.0.6 on 2022-08-03 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='电影名')),
                ('file', models.ImageField(blank=True, null=True, upload_to='ToolBox/MovieRank/%Y/%m/%d/', verbose_name='海报图')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='影评')),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_next', to='MovieRank.movie', verbose_name='后结点')),
                ('pre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_pre', to='MovieRank.movie', verbose_name='前结点')),
            ],
        ),
    ]
