# Generated by Django 4.0.6 on 2022-08-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='file',
            new_name='poster',
        ),
    ]
