# Generated by Django 4.0.3 on 2022-04-12 07:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notebook_directory',
            fields=[
                ('directory_id', models.AutoField(primary_key=True, serialize=False, verbose_name='目录id')),
                ('directory_name', models.CharField(max_length=20, verbose_name='目录名')),
                ('directory_discription', models.CharField(blank=True, max_length=100, null=True, verbose_name='目录描述')),
                ('directory_createdDate', models.DateTimeField(default=datetime.datetime(2022, 4, 12, 15, 2, 46, 788531), verbose_name='目录创建时间')),
                ('directory_parentDir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notebook.notebook_directory', verbose_name='父目录')),
            ],
            options={
                'verbose_name': '目录',
                'verbose_name_plural': '目录',
            },
        ),
        migrations.CreateModel(
            name='notebook_note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False, verbose_name='笔记id')),
                ('note_title', models.CharField(max_length=50, verbose_name='笔记标题')),
                ('note_content', models.TextField(verbose_name='笔记内容')),
                ('note_pinTop', models.BooleanField(default=False, verbose_name='置顶')),
                ('note_pending', models.BooleanField(default=True, verbose_name='待编辑')),
                ('note_createDate', models.DateTimeField(default=datetime.datetime(2022, 4, 12, 15, 2, 46, 789607), verbose_name='笔记创建时间')),
                ('note_editDate', models.DateTimeField(auto_now_add=True, verbose_name='笔记修改时间')),
                ('note_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notebook.notebook_directory', verbose_name='所属目录')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
            },
        ),
        migrations.CreateModel(
            name='notebook_note_alert',
            fields=[
                ('note_alert_id', models.AutoField(primary_key=True, serialize=False, verbose_name='提醒id')),
                ('note_alert_datetime', models.DateTimeField(verbose_name='提醒时间')),
                ('note_alert_note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notebook.notebook_note', verbose_name='所属笔记')),
            ],
            options={
                'verbose_name': '提醒',
                'verbose_name_plural': '提醒',
            },
        ),
    ]
