# Generated by Django 4.0.3 on 2022-04-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook_directory',
            name='directory_createdDate',
            field=models.DateTimeField(verbose_name='目录创建时间'),
        ),
        migrations.AlterField(
            model_name='notebook_note',
            name='note_createDate',
            field=models.DateTimeField(verbose_name='笔记创建时间'),
        ),
    ]
