# Generated by Django 4.0.3 on 2022-04-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0003_alter_notebook_note_note_createdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook_note',
            name='note_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notebook.notebook_directory', verbose_name='所属目录'),
        ),
    ]
