# Generated by Django 4.0.3 on 2022-04-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0006_notebook_note_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook_note',
            name='note_content',
            field=models.TextField(blank=True, null=True, verbose_name='笔记内容'),
        ),
    ]
