# Generated by Django 4.0.3 on 2022-04-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0007_alter_notebook_note_note_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='notebook_userfile',
            fields=[
                ('userfile_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文件id')),
                ('userfile_content', models.FileField(upload_to='Notebook/%Y/%m/%d/', verbose_name='文件内容')),
            ],
        ),
    ]
