# Generated by Django 4.0.3 on 2022-04-20 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0008_notebook_userfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook_directory',
            name='directory_createdDate',
        ),
        migrations.RemoveField(
            model_name='notebook_directory',
            name='directory_parentDir',
        ),
        migrations.AddField(
            model_name='notebook_directory',
            name='directory_first_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_child', to='Notebook.notebook_directory', verbose_name='第一个子目录（左子树）'),
        ),
        migrations.AddField(
            model_name='notebook_directory',
            name='directory_next_brother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_brother', to='Notebook.notebook_directory', verbose_name='下一个同级目录（右子树）'),
        ),
    ]
