# Generated by Django 4.0.3 on 2022-04-28 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notebook', '0011_alter_notebook_directory_directory_first_child_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook_note_alert',
            old_name='note_alert_datetime',
            new_name='alert_datetime',
        ),
        migrations.RenameField(
            model_name='notebook_note_alert',
            old_name='note_alert_id',
            new_name='alert_id',
        ),
        migrations.RenameField(
            model_name='notebook_note_alert',
            old_name='note_alert_note_id',
            new_name='alert_note',
        ),
        migrations.AddField(
            model_name='notebook_directory',
            name='directory_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook_note',
            name='note_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook_userfile',
            name='userfile_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
            preserve_default=False,
        ),
    ]
