# Generated by Django 4.0.3 on 2022-04-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0012_rename_note_alert_datetime_notebook_note_alert_alert_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook_note',
            name='note_pending',
            field=models.BooleanField(default=False, verbose_name='待编辑'),
        ),
    ]
