# Generated by Django 4.0.3 on 2022-04-29 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notebook', '0013_alter_notebook_note_note_pending'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notebook_note',
            new_name='note',
        ),
        migrations.RenameModel(
            old_name='notebook_directory',
            new_name='directory',
        ),
        migrations.RenameModel(
            old_name='notebook_note_alert',
            new_name='alert',
        ),
        migrations.RenameModel(
            old_name='notebook_userfile',
            new_name='userfile',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_datetime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_createDate',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_editDate',
            new_name='editDate',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_pending',
            new_name='isPending',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_pinTop',
            new_name='isPinTop',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userfile',
            old_name='userfile_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='userfile',
            old_name='userfile_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userfile',
            old_name='userfile_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_directory',
            new_name='direcoty',
        ),
    ]
