# Generated by Django 4.0.3 on 2022-04-29 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0014_directory_rename_notebook_note_alert_alert_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='directory_discription',
            new_name='discription',
        ),
        migrations.RenameField(
            model_name='directory',
            old_name='directory_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='directory',
            old_name='directory_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='directory',
            old_name='directory_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='direcoty',
            new_name='directory',
        ),
        migrations.RenameField(
            model_name='directory',
            old_name='directory_first_child',
            new_name='first_child',
        ),
        migrations.RenameField(
            model_name='directory',
            old_name='directory_next_brother',
            new_name='next_brother',
        ),
    ]
