# Generated by Django 4.0.3 on 2022-04-29 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0015_rename_directory_discription_directory_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='first_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_first_child', to='Notebook.directory', verbose_name='第一个子目录（左子树）'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='next_brother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_next_brother', to='Notebook.directory', verbose_name='下一个同级目录（右子树）'),
        ),
    ]
