# Generated by Django 4.0.3 on 2022-06-16 05:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notebook', '0016_alter_directory_first_child_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userfile',
            new_name='note_file',
        ),
    ]
