# Generated by Django 4.0.3 on 2022-06-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0017_rename_userfile_note_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note_file',
            old_name='content',
            new_name='file',
        ),
    ]
