# Generated by Django 4.0.3 on 2022-06-16 06:46

import Notebook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0022_alter_note_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_file',
            name='file',
            field=models.FileField(upload_to=Notebook.models.file_path, verbose_name='文件内容'),
        ),
    ]
