# Generated by Django 4.0.3 on 2022-06-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0025_alter_note_file_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='isPending',
            new_name='isUnfinished',
        ),
        migrations.AlterField(
            model_name='note',
            name='isUnfinished',
            field=models.BooleanField(default=True, verbose_name='待编辑'),
        ),
    ]
