# Generated by Django 4.0.3 on 2022-07-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebook', '0026_rename_note_isunfinished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note_file',
            options={'verbose_name': '文件', 'verbose_name_plural': '文件'},
        ),
        migrations.AddField(
            model_name='note',
            name='shortcut',
            field=models.BooleanField(default=False, verbose_name='快捷方式'),
        ),
    ]
