# Generated by Django 4.0.6 on 2023-01-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='masturbation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='Rocky', max_length=20, verbose_name='用户')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
    ]
