# Generated by Django 4.0.6 on 2023-03-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CafeFrame', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masturbation',
            options={'verbose_name': '首充记录', 'verbose_name_plural': '首充记录'},
        ),
    ]
