# Generated by Django 4.2 on 2023-05-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeFrame', '0002_alter_masturbation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masturbation',
            name='createDate',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
